const now = new Date();
const getMonth = (dt: Date, add: number = 0) => {
	let month = dt.getMonth() + 1 + add;
	const str = (month < 10 ? '0' + month : month).toString();
	return str;
	// return dt.getMonth() < 10 ? '0' + month : month;
};
export const data_holiday_schedule = [
	{
		id: 1,
		user: 'Staff_A',
		title: 'Tết dương',
		start: now.getFullYear() + '-' + getMonth(now) + '-01T14:30:00',
		end: now.getFullYear() + '-' + getMonth(now) + '-01T15:30:00',
		// className: 'danger',
		description: 'Chi tiết về ngày lễ',
	},
	{
		id: 2,
		user: 'Staff_B',
		title: 'Tết nguyên đán',
		start: now.getFullYear() + '-' + getMonth(now) + '-07T19:30:00',
		end: now.getFullYear() + '-' + getMonth(now) + '-08T14:30:00',
		// className: 'primary',
		description: 'Chi tiết về ngày lễ',
	},
	{
		id: 3,
		user: 'Staff_C',
		title: 'Giỗ tổ',
		start: now.getFullYear() + '-' + getMonth(now) + '-17T14:30:00',
		end: now.getFullYear() + '-' + getMonth(now) + '-18T14:30:00',
		// className: 'info',
		description: 'Chi tiết về ngày lễ',
	},
	{
		id: 4,
		user: 'Staff_D',
		title: 'Quốc khánh',
		start: now.getFullYear() + '-' + getMonth(now) + '-12T10:30:00',
		end: now.getFullYear() + '-' + getMonth(now) + '-13T10:30:00',
		// className: 'danger',
		description: 'Chi tiết về ngày lễ',
	},
	{
		id: 5,
		user: 'Staff_E',
		title: 'Lễ 5',
		start: now.getFullYear() + '-' + getMonth(now) + '-12T15:00:00',
		end: now.getFullYear() + '-' + getMonth(now) + '-13T15:00:00',
		// className: 'info',
		description: 'Chi tiết về ngày lễ',
	},
	{
		id: 6,
		user: 'Staff_F',
		title: 'Lễ 6',
		start: now.getFullYear() + '-' + getMonth(now) + '-12T21:30:00',
		end: now.getFullYear() + '-' + getMonth(now) + '-13T21:30:00',
		// className: 'success',
		description: 'Chi tiết về ngày lễ',
	},
	{
		id: 7,
		user: 'Staff_G',
		title: 'Lễ 7',
		start: now.getFullYear() + '-' + getMonth(now) + '-12T05:30:00',
		end: now.getFullYear() + '-' + getMonth(now) + '-13T05:30:00',
		// className: 'info',
		description: 'Chi tiết về ngày lễ',
	},
	{
		id: 8,
		user: 'Staff_H',
		title: 'Lễ 8',
		start: now.getFullYear() + '-' + getMonth(now) + '-12T20:00:00',
		end: now.getFullYear() + '-' + getMonth(now) + '-13T20:00:00',
		// className: 'danger',
		description: 'Chi tiết về ngày lễ',
	},
	{
		id: 9,
		user: 'Staff_I',
		title: 'Lễ 9',
		start: now.getFullYear() + '-' + getMonth(now) + '-27T20:00:00',
		end: now.getFullYear() + '-' + getMonth(now) + '-28T20:00:00',
		// className: 'success',
		description: 'Chi tiết về ngày lễ',
	},
	{
		id: 10,
		user: 'Staff_K',
		title: 'Lễ 10',
		start: now.getFullYear() + '-' + getMonth(now, 1) + '-24T08:12:14',
		end: now.getFullYear() + '-' + getMonth(now, 1) + '-27T22:20:20',
		// className: 'danger',
		description: 'Chi tiết về ngày lễ',
	},
	{
		id: 11,
		user: 'Staff_L',
		title: 'Lễ 11',
		start: now.getFullYear() + '-' + getMonth(now, -1) + '-13T08:12:14',
		end: now.getFullYear() + '-' + getMonth(now, -1) + '-16T22:20:20',
		// className: 'primary',
		description: 'Chi tiết về ngày lễ',
	},
	{
		id: 13,
		user: 'Staff_M',
		title: 'Lễ 13',
		start: now.getFullYear() + '-' + getMonth(now, 1) + '-15T08:12:14',
		end: now.getFullYear() + '-' + getMonth(now, 1) + '-18T22:20:20',
		// className: 'primary',
		description: 'Chi tiết về ngày lễ',
	},
];
