name: Node.js CI

on:
    push:
        branches: [dev]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy using ssh
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: 22
                  script: |
                      cd /home/vangtats/HRM_FE
                      git pull origin master
                      git status
                      docker compose up -b --build
