name: Build HRM_FE

on:
    pull_request:
        branches: [dev]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v1
            - run: bun i
            - name: 'Create env file'
              run: |
                  touch .env
                  echo NEXT_PUBLIC_BE_URL=${{ secrets.NEXT_PUBLIC_BE_URL }} >> .env
            - run: bun run build
            - name: 'Tar build files'
              run: tar -cvf build.tar .next
            - name: 'Upload build.tar'
              uses: actions/upload-artifact@v4
              with:
                  name: build
                  path: build.tar

    test:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/download-artifact@v4
              with:
                  name: build
            - run: tar -xvf build.tar
            - uses: oven-sh/setup-bun@v1
            - name: Install playwright
              run: npx playwright install chromium
            - run: bun i @playwright/test
            - name: Run e2e tests
              run: npx playwright test
            - name: 'Tar report files'
              if: always()
              run: tar -cvf report.tar playwright-report
            - name: 'Upload report.tar'
              if: always()
              run: |
                  sshpass -p "${{ secrets.PASSWORD }}" scp -o StrictHostKeyChecking=no report.tar ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/vangtats/HRM_FE/report/report_${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}.tar
            - name: Extract report using
              if: always()
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: 22
                  script: |
                      cd /home/vangtats/report
                      tar -xvf report_${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}.tar
            - name: Publish Summary
              if: always()
              run: |
                  echo -e "## 📊 Test Summary\n\n- [Test Report](http://test.abc)" >> $GITHUB_STEP_SUMMARY
