name: Build HRM_FE

on:
    pull_request:
        branches: [dev]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: oven-sh/setup-bun@v1
            - run: bun i
            - run: bun run build
            - name: 'Tar build files'
              run: tar -cvf build.tar .next
            - name: 'Upload build.tar'
              uses: actions/upload-artifact@v4
              with:
                  name: build
                  path: build.tar

    test:
        needs: build
        runs-on: ubuntu-latest
        container:
            image: mcr.microsoft.com/playwright:v1.42.1-jammy
        steps:
            - uses: actions/download-artifact@v4
              with:
                  name: build
            - uses: oven-sh/setup-bun@v1
            - name: Install playwright
              run: npx playwright install
            - name: Run e2e tests
              run: npx playwright test
