name: Build HRM_FE

on:
    pull_request:
        branches: [dev]

jobs:
    # build:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - uses: actions/checkout@v2
    #         - uses: actions/setup-node@v2
    #           with:
    #               node-version: 18.x
    #         - run: npm i --force
    #         - run: npm run build --if-present
    test:
        runs-on: ubuntu-latest
        container:
            image: mcr.microsoft.com/playwright:v1.42.1-jammy
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 18.x
            - name: Install dependencies
              run: npm i --force
            - name: Build app
              run: npm run build --if-present
            - name: Start local server
              run: npm run start
            - name: Run your tests
              run: npm run test
              env:
                  HOME: /root
