name: Build HRM_FE

on:
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 18
      uses: actions/setup-node@v2
      with:
        node-version: 18.x
    - run: npm i --force
    - run: npm run build --if-present
