name: Node.js CI

on:
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get source branch
        run: echo "Source branch is ${{ github.head_ref }}"

      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            port: 22
            script: |
                cd /home/vangtats/ci/HRM_FE
                git pull origin ${{ github.head_ref }}
                git status
                docker compose up -b --build
